# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/XILINX/Projects/sobel_operataion/sobel_new/sobel_new.srcs/sobel_top/ip/sobel_top_matrix_3r3c_0_0/sobel_top_matrix_3r3c_0_0.xci
# IP: The module: 'sobel_top_matrix_3r3c_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/XILINX/Projects/sobel_operataion/sobel_new/sobel_new.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# XDC: e:/XILINX/Projects/sobel_operataion/sobel_new/sobel_new.srcs/sobel_top/ip/sobel_top_matrix_3r3c_0_0/sobel_top_matrix_3r3c_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sobel_top_matrix_3r3c_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/XILINX/Projects/sobel_operataion/sobel_new/sobel_new.srcs/sobel_top/ip/sobel_top_matrix_3r3c_0_0/sobel_top_matrix_3r3c_0_0.xci
# IP: The module: 'sobel_top_matrix_3r3c_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/XILINX/Projects/sobel_operataion/sobel_new/sobel_new.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# XDC: e:/XILINX/Projects/sobel_operataion/sobel_new/sobel_new.srcs/sobel_top/ip/sobel_top_matrix_3r3c_0_0/sobel_top_matrix_3r3c_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sobel_top_matrix_3r3c_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
